name: Dart

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install Flutter
      - uses: britannio/action-install-flutter@v1.1
